# Get editor completions based on the config system
"$schema" = "https://starship.rs/config-schema.json"

# Do not insert a blank line between shell prompts
add_newline = false

format = '$os$battery$git_branch$git_status$hostname\[$directory\]$character'

[os]
disabled = false

# Replace the 'â¯' symbol in the prompt with 'âœ'
[character] # THe name of the module
success_symbol = '[âœ](bold green)'

[directory]
format = '[$path]($style)'

[hostname]
ssh_only = true
format = '[$ssh_symbol$hostname]($style)'

[package]
disabled = true

[battery]
full_symbol = 'ğŸ”‹ '
charging_symbol = 'âš¡ï¸ '
discharging_symbol = 'ğŸ’€ '

[memory_usage]
disabled = true
threshold = -1
style = 'bold green dimmed'
format = '${ram_pct}'

[git_branch]
format = '[$symbol$branch]($style)'
ignore_branches = ['master','main']

[git_status]
conflicted = 'ğŸ³'
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'
untracked = 'ğŸ¤·'
stashed = 'ğŸ“¦'
modified = 'ğŸ“'
staged = '[++\($count\)](green)'
renamed = 'ğŸ‘…'
deleted = 'ğŸ—‘'
